name: Custom Youtube Market Research

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      search_query:
        description: '検索キーワード'
        required: true
        default: '龍が如く3'
      video_duration:
        description: '動画の長さ'
        required: true
        default: 'short'
        type: choice
        options: [any, short, medium, long]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-api-python-client pandas jinja2

      - name: Run research script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          INPUT_QUERY: ${{ github.event.inputs.search_query }}
          INPUT_DURATION: ${{ github.event.inputs.video_duration }}
        run: python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages # ★ここをWebサイト用にする
